
#Rhea Lingaiah
#rlingaia@ucsc.edu
#12M
#7/14/17	
JAVASRC	=	FileReverse.java
SOURCES	= README Makefile $(JAVASRC)
MAINCLASS	=FileReverse
CLASSES	=	FileReverse.class
JARFILE	=FileReverse
SUBMIT	=submit cmps012b-pt.u17 lab2
all:	$(JARFILE)
$(JARFILE): $(CLASSES)
	echo Main-class: $(MAINCLASS) > Manifest
	jar cvfm $(JARFILE) Manifest $(CLASSES)
	rm Manifest
	chmod +x $(JARFILE)
$(CLASSES): $(JAVASRC)
	javac -Xlint $(JAVASRC)
clean:
	rm $(CLASSES)	$(JARFILE)
submit:	$(SOURCES)
	$(SUBMIT)	$(SOURCES)
